// GET LIST
export const GET_TASKS_LIST = 'GET_TASK_LIST'

// ADD A TASK
export const ADD_TASK = 'ADD_TASK'

// CHANGE STATUS
export const CHANGE_STATUS = 'CHANGE_STATUS'

// EDIT TASK
export const EDIT_TASK = 'EDIT_TASK'

//   DELETE TASK
export const DELETE_TASK = 'DELETE_TASK'
